development:
  adapter: postgresql
  encoding: unicode
  database: BEF_development
  pool: 5
  username: BEF
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: BEF_test
  pool: 5
  username: BEF
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: BEF_production
  pool: 5
  username: BEF
  password:
