development:
  host: localhost
  port: 3000
  protocol: http
  s3:
    bucket: bef-development
    access_key_id:
      environment: S3_ACCESS_KEY_ID
    secret_access_key:
      environment: S3_SECRET_ACCESS_KEY

test:
  host: localhost
  port: 9887
  protocol: http
  s3:
    bucket: bef-test

staging:
  host: bef-stage.herokuapp.com
  port:
  protocol: http
  s3:
    bucket: bef-staging
    access_key_id:
      environment: S3_ACCESS_KEY_ID
    secret_access_key:
      environment: S3_SECRET_ACCESS_KEY

production:
  host: siliconvalleybadgers.com
  port:
  protocol: http
  s3:
    bucket: bef-production
    access_key_id:
      environment: S3_ACCESS_KEY_ID
    secret_access_key:
      environment: S3_SECRET_ACCESS_KEY
