development:
  host: localhost
  port: 3000
  protocol: http

test:
  host: localhost
  port: 9887
  protocol: http

staging:
  host: bef-stage.herokuapp.com
  port:
  protocol: http

production:
  host: siliconvalleybadgers.com
  port:
  protocol: http
